PIDGIN_MAP = {
    'wetin': 'what-in',
    'dey': 'day',
    'abeg': 'please',
    'na': 'is',
    'wey': 'way',
    'comot': 'come-out',
    'sabi': 'sah-bee',
    'chop': 'eat',
    'vex': 'vayx',
    'palava': 'pah-lah-vah',
    'taya': 'tire',
    'wahala': 'wah-hah-lah',
    'kolo': 'koh-loh',
    'yab': 'yap',
    'gimme': 'give-me',
    'howfa': 'how-far',
    'no wahala': 'no wah-hah-lah',
    'oga': 'oh-gah',
    'madam': 'mah-dam',
    'pikin': 'pee-kin',
    'tori': 'toh-ree',
    'yarn': 'yahn',
    'jare': 'jah-ray',
    'sharply': 'shahp-lee',
    'commot': 'come-out',
    'jollof': 'jol-off',
    'boku': 'boo-koo',
    'kpatakpata': 'kpah-tah-kpah-tah',
    'nawa': 'nah-wah',
    'shuo': 'shoo-oh',
    'ehen': 'eh-hen',
    'chai': 'chy',
    'nna': 'nah',
    'kuku': 'koo-koo',
    'gbam': 'gbahm',
    'waka': 'wah-kah',
    'troway': 'throw-way',
    'fit': 'feet',
    'dey go': 'day go',
    'don': 'done',
    'siddon': 'sit-down',
    'carry': 'kah-ree',
    'hala': 'hah-lah',
    'mumu': 'moo-moo',
    'yeye': 'yay-yay',
    'olodo': 'oh-loh-doh',
    'akamu': 'ah-kah-moo',
    'oyibo': 'oh-yee-boh',
    'beta': 'beh-tah',
    'chook': 'chook',
    'gbese': 'gbeh-say',
    'kpef': 'kpeff',
    'oshey': 'oh-shay',
    'biko': 'bee-koh',
    'kain': 'kayn',
    'sef': 'self',
    'jara': 'jah-rah',
    'kpai': 'kpie',
    'shikena': 'shee-keh-nah',
    'how you dey': 'how you day',
    'wetin you dey do': 'what-in you day do',
    'make we go': 'make we go',
    'no dey': 'no day',
    'e don do': 'it done do',
    'who be dat': 'who be that',
    'na so': 'is so',
    'chop money': 'eat money',
    'troway face': 'throw-way face',
    'shakara': 'shah-kah-rah',
    'kack up': 'kack up',
    'ogbonge': 'ohg-bohn-gay',
    'pepper dem': 'pep-per dem',
    'shine your eye': 'shine your eye',
    'no dull': 'no dull',
    'belle full': 'bell-ee full',
    'e get as e be': 'it get as it be',
    'scatter everywhere': 'scat-ter every-where',
    'hustle': 'huss-ul',
    'levels don change': 'lev-uls done change',
    'abeg who get dis': 'please who get this',
    'make i yarn you': 'make i yahn you',
    'no vex me o': 'no vayx me oh',
    'e be like': 'it be like',
    'chop remain': 'eat remain',
    'waka well': 'wah-kah well',
    'no do yanga': 'no do yan-gah',
    'tins dey happen': 'things day happen',
    'i dey feel you': 'i day feel you',
    'correct guy': 'cor-rect guy',
    'wetin dey play': 'what-in day play',
    'i don tire': 'i done tire',
    'make we chop': 'make we eat',
    'no be small tin': 'no be small thing',
    'abeg show face': 'please show face',
    'oga how far': 'oh-gah how far',
    'no whine me': 'no wine me',
    'e dey sweet me': 'it day sweet me',
    'make e no spoil': 'make it no spoil',
    'wetin dey ground': 'what-in day ground',
}

def preprocess_pidgin(text):
    text = text.lower()
    for pidgin, english in sorted(PIDGIN_MAP.items(), key=lambda x: len(x[0]), reverse=True):
        text = text.replace(f' {pidgin} ', f' {english} ')
        text = text.replace(f' {pidgin}.', f' {english}.')
        text = text.replace(f' {pidgin},', f' {english},')
    return text