services:
  - type: web
    name: readout
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn core.wsgi
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your-secret-key-here
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        sync: false  # render auto-injects the actual DB URL
