# Generated by Django 5.2.3 on 2025-06-25 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversion',
            name='title',
        ),
    ]
