# Generated by Django 5.2.3 on 2025-06-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pid', 'Pidgin')], default='en', max_length=10),
        ),
    ]
