# Generated by Django 5.2.3 on 2025-06-25 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_remove_conversion_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
    ]
